apiVersion: v1
kind: Secret
metadata:
  name: intics-dhub-token
  namespace: bronze
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJhdXRoIjogImVuTjFZbk5qY21sd2RHbHZianBrWTJ0eVgzQmhkRjl0WDNkTVJWZDVUVEpZVmtwYVFUTlhSRjlHWVRkVFZFMU9ORVU9IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
