apiVersion: v1
kind: Secret
metadata:
  name: metrics-dashboard-secrets
  namespace: bronze
type: Opaque
stringData:
  # Database Password
  SPRING_DATASOURCE_PASSWORD: "xaX48cgDymcHwq5"
  
  # Email Password (SMTP)
  SPRING_MAIL_PASSWORD: "qvpkyekqmsggsffo"
