apiVersion: v1
kind: Secret
metadata:
  name: metrics-dashboard-secrets
  namespace: bronze
type: Opaque
stringData:
  # Base64 encode these values before applying to cluster
  db-password: "xaX48cgDymcHwq5"
  mail-username: "inticsai@gmail.com"
  mail-password: "qvpkyekqmsggsffo"
