server.port=${SERVER_PORT}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database Configuration (from environment variables)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Connection Pool Settings (from environment variables)
spring.datasource.hikari.maximum-pool-size=${HIKARI_MAX_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${HIKARI_MIN_IDLE}
spring.datasource.hikari.connection-timeout=${HIKARI_CONNECTION_TIMEOUT}
spring.datasource.hikari.idle-timeout=${HIKARI_IDLE_TIMEOUT}
spring.datasource.hikari.leak-detection-threshold=${HIKARI_LEAK_DETECTION_THRESHOLD}

# Logging Configuration
logging.level.com.intics=INFO
logging.level.org.springframework.web=INFO

# Email Configuration (SMTP - from environment variables)
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.debug=false


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always



# Notification Settings
notification.email.from=${NOTIFICATION_EMAIL_FROM}
notification.email.to=${NOTIFICATION_EMAIL_TO}

management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.health.elasticsearch.enabled=false
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=health,loggers,metrics,quartz,threaddump,heapdump,logfile,prometheus,env
management.metrics.enable.jvm=true

# ========================================
# Azure AD Token Generation
# ========================================
# Enable Azure AD token generation (default: false)

azure.token.enabled=false

# Azure AD Configuration (only used when azure.token.enabled=true)


# Azure AD Configuration (only used when azure.token.enabled=true) add
azure.identity.tenantId=2f30df36-e5b3-4199-ae1e-c03c7409c3e4
azure.identity.clientId=ed93943a-ed6f-4de4-a8a3-880b851a07b1
azure.identity.clientSecret=${AZURE_CLIENT_SECRET}
azure.token.scope=https://ossrdbms-aad.database.windows.net/.default


